### ISSUE TITLE
UINavigationItem.leftBarButtonItems are positioned incorrectly in iPad landscape

### ISSUE THREAD

**Issue by mplorentz** [macteo/SabBar#1]
We are using a `SabBar` as the main tab bar controller for our app. In some view controllers we have `UIBarButtonItems` that are set to the `leftBarButtonItem` property of the `UINavigationItem`. Unfortunately the `SabBar` creates a space between the left edge of the screen and the left bar button item on an iPad in landscape. See the attached screenshot: 
![untitled](https://cloud.githubusercontent.com/assets/1165004/16319822/c0fad572-3962-11e6-980f-2517ecdc724a.png)
How do you recommend dealing with this situation? Somehow the navigation controller knows to draw the navigation bar on top of the `SabBar`, but it won't use that space for bar button items.

**Comment by macteo** [comment]
Hi,
based on the screenshot you posted I'm not completely sure about your configuration, however, the expected behaviour is that the navigation bar (the one with the funnel) will start from the right of the limit of the left side bar. The portion of the navigation bar below the carrier name is a completely different navigation bar, with the same interface configuration of the right one, so you cannot fill it with an item. However you can use the [`headerView`](http://cocoadocs.org/docsets/SabBar/0.9.1/Classes/SabBarController.html#/s:vC6SabBar16SabBarController10headerViewGSqCSo6UIView_) property to add a button there. If you want to change the behaviour, you could try to embed the tab bar inside a navigation controller and don't display the inner navigation bar. However this way the tabs will be pushed when you present another controller and become hidden.

**Comment by mplorentz** [comment]
Ok, thanks for the suggestions. I may modify our SabBar to remove the navigation bar from below the carrier name, but I don't think that would look very nice either. If we implement a solution that would be useful to others I will submit a PR.
